### ISSUE TITLE
Any plan's for an AsyncReporter?

### ISSUE THREAD

**Issue by tommy-muehle** [GoogleCloudPlatform/google-cloud-php-trace#1]
Hi guys,

firstly thanks for providing this library! Did you have any plan's to provide an AsyncReporter in future? If that are possible.

Best regards,
Tommy

**Comment by dwsupplee** [comment]
Hey @tommy-muehle,

This is actually in the works right now! @chingor13 should be able to share some more information on the progress.

**Comment by chingor13** [comment]
Yes, it's already been implemented, but due to the nature of how PHP servers run, we need to use an external process. The [batch branch](https://github.com/GoogleCloudPlatform/google-cloud-php/tree/batch) is introducing a mechanism for both batching and asynchronously making API requests at runtime. This is especially useful for stuff like logging, error reporting, pub/sub, and tracing.

[PR for AsyncReporter](https://github.com/GoogleCloudPlatform/google-cloud-php/pull/548)

**Comment by chingor13** [comment]
This should be available in version 0.2.0 of google/cloud-trace (part of 0.33.0 of google/cloud).

**Comment by jdpedrie** [comment]
* [google/cloud#v0.33.0](https://github.com/GoogleCloudPlatform/google-cloud-php/releases/tag/v0.33.0)
* [google/cloud-trace#v0.2.0](https://github.com/GoogleCloudPlatform/google-cloud-php-trace/releases/tag/v0.2.0).
